### ISSUE TITLE
May I ask how coverage_roberta.bin and gpt2_med_cp90.bin are generated?

### ISSUE THREAD

**Issue by laosuan** [tingofurro/keep_it_simple#5]
May I ask how coverage_roberta.bin and gpt2_med_cp90.bin are generated? Can you provide the relevant code? Thank you.

**Comment by tingofurro** [comment]
Hey @laosuan,

Thanks for your question. They're both from our prior work Summary Loop, and you can find the training script of the GitHub repo for that project: https://github.com/CannyLab/summary_loop/

I hope this helps,

Philippe

**Comment by laosuan** [comment]
Thank you a lot!
